import { ArrowLeft, Phone, ChevronDown, BookOpen, Brain, ScanSearch, ClipboardList, PackageCheck, FileSignature, CheckCircle, Shield } from 'lucide-react';
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';

export function MovingGuidePage() {
  const navigate = useNavigate();
  const [openIndex, setOpenIndex] = useState<number | null>(null);
  useEffect(() => { window.scrollTo(0, 0); }, []);

  const sections = [
    { icon: <BookOpen className="w-6 h-6 text-blue-600" />, title: '1. Redéfinir le déménagement à l\'ère du numérique', content: (<><p className="mb-3">Historiquement, le déménagement (du latin <em>demano</em>, se répandre, et <em>demunitio</em>, retrancher) était perçu comme un chaos nécessaire, une <strong>source de stress majeure</strong> (la 3ème en France).</p><div className="bg-blue-50 border-l-4 border-blue-500 p-4 rounded-r-lg"><p>Chez <strong>Trouve Ton Déménageur</strong>, nous redéfinissons cette étape : le déménagement n&apos;est plus un « remue-ménage » incertain, mais une <strong>transition sécurisée par la donnée</strong>. Grâce à notre plateforme, vous ne déplacez pas seulement des meubles, vous bénéficiez d&apos;une infrastructure technologique qui protège votre patrimoine tout au long de son voyage.</p></div></>) },
    { icon: <Shield className="w-6 h-6 text-green-600" />, title: '2. Les points forts de la plateforme TTD', content: (<><p className="mb-3">Pourquoi choisir trouvetondemenageur.fr plutôt qu&apos;une recherche classique ?</p><div className="space-y-3"><div className="bg-green-50 rounded-lg p-3"><strong>Sélection « Elite » des prestataires :</strong> Contrairement aux annuaires classiques, chaque déménageur sur TTD est soumis à un audit juridique strict (Licence de transport, Kbis, Assurance RC Pro et Marchandises à jour).</div><div className="bg-green-50 rounded-lg p-3"><strong>Transparence tarifaire :</strong> Finies les surprises. Le prix de la prestation est établi sur la base des informations fournies par le Client lors de la réservation.</div><div className="bg-green-50 rounded-lg p-3"><strong>Intermédiation de confiance :</strong> Nous agissons comme un tiers de confiance, garantissant que chaque partie respecte ses engagements contractuels.</div></div></>) },
    { icon: <Brain className="w-6 h-6 text-purple-600" />, title: '3. L\'Innovation Majeure : Le Protocole de Preuve par IA 🤖', content: (<><p className="mb-3">C&apos;est ici que TTD se distingue sur le marché. Nous intégrons un <strong>protocole de preuve numérique par Intelligence Artificielle</strong>.</p><p className="mb-3 font-semibold">Comment fonctionne votre bouclier visuel ?</p><div className="space-y-3"><div className="bg-purple-50 rounded-lg p-3"><strong>Capture sécurisée :</strong> Avant le chargement, vous documentez l&apos;état de vos biens via notre outil de capture photo.</div><div className="bg-purple-50 rounded-lg p-3"><strong>Analyse de données :</strong> Ces images sont horodatées et intégrées à votre dossier numérique.</div><div className="bg-purple-50 rounded-lg p-3"><strong>Rapport Technique d&apos;Analyse :</strong> En cas de litige à la livraison, notre IA compare les clichés « Avant/Après ». Elle génère un Rapport Technique de Constatation qui identifie les dommages avec une précision millimétrique. Ce document constitue un élément technique pouvant faciliter la constitution d&apos;un dossier de déclaration auprès de l&apos;assureur du déménageur.</div></div></>) },
    { icon: <ClipboardList className="w-6 h-6 text-orange-600" />, title: '4. Votre feuille de route pour un succès total', content: (<><div className="space-y-4"><div className="bg-orange-50 rounded-xl p-4"><h3 className="font-bold text-orange-900 mb-2">Étape 1 : Le calcul de volume intelligent</h3><p>Ne sous-estimez plus votre cubage. Utilisez notre outil en ligne pour lister vos pièces. Un volume précis, c&apos;est l&apos;assurance d&apos;un camion adapté et d&apos;un prix juste.</p></div><div className="bg-blue-50 rounded-xl p-4"><h3 className="font-bold text-blue-900 mb-2">Étape 2 : La préparation « Expert »</h3><p className="mb-2"><strong>Cartons spécifiques :</strong> Utilisez des cartons renforcés pour le lourd (livres) et des croisillons pour le fragile (verres).</p><p><strong>Le marquage :</strong> Identifiez chaque carton par pièce. Notre protocole pourra ainsi vous aider à vérifier que tout est bien arrivé à destination.</p></div><div className="bg-green-50 rounded-xl p-4"><h3 className="font-bold text-green-900 mb-2">Étape 3 : Le jour J et la Lettre de Voiture</h3><p>Le chef d&apos;équipe vous présente la Lettre de Voiture. C&apos;est le contrat de transport officiel. Grâce à TTD, ce document est complété par votre inventaire photo numérique, créant un écosystème de preuve à force probante renforcée.</p></div><div className="bg-purple-50 rounded-xl p-4"><h3 className="font-bold text-purple-900 mb-2">Étape 4 : La livraison et la clôture</h3><p>Inspectez vos biens lors de la livraison. Si tout est conforme, la prestation est considérée comme terminée entre vous et le Déménageur conformément au contrat de transport.</p></div></div></>) },
    { icon: <CheckCircle className="w-6 h-6 text-emerald-600" />, title: 'Pourquoi TTD est votre meilleur allié ?', content: (<><p className="mb-3">Le déménagement « seul » semble économique, mais il vous expose à des risques physiques et financiers colossaux. En passant par un professionnel via TTD, vous achetez la sérénité.</p><div className="bg-emerald-50 border-l-4 border-emerald-500 p-4 rounded-r-lg"><p className="font-semibold text-emerald-900">Trouve Ton Déménageur transforme une épreuve humaine en une formalité logistique fluide, où l&apos;Intelligence Artificielle devient le garant de votre tranquillité.</p></div></>) },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50">
      <div className="max-w-5xl mx-auto px-4 py-8">
        <button onClick={() => navigate(-1)} className="flex items-center gap-2 text-blue-600 hover:text-blue-800 mb-6 group"><ArrowLeft className="w-5 h-5 group-hover:-translate-x-1 transition-transform" /><span className="font-medium">Retour</span></button>
        <main>
          <div className="text-center mb-12">
            <h1 className="text-4xl font-extrabold text-gray-900 mb-3">Guide : Le Déménagement Nouvelle Génération avec TTD</h1>
            <p className="text-xl text-gray-500">L&apos;alliance de l&apos;expertise humaine et de l&apos;Intelligence Artificielle</p>
          </div>
          <div className="space-y-3">
            {sections.map((section, index) => { const isOpen = openIndex === index; return (<div key={index} className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden"><button onClick={() => setOpenIndex(isOpen ? null : index)} className="w-full px-8 py-6 flex items-center justify-between text-left hover:bg-gray-50 transition-colors"><div className="flex items-center gap-3 pr-4">{section.icon}<span className="text-lg font-semibold text-gray-900">{section.title}</span></div><ChevronDown className={`w-6 h-6 text-gray-400 flex-shrink-0 transition-transform ${isOpen ? 'rotate-180' : ''}`} /></button>{isOpen && <div className="px-8 pb-6 text-gray-700 leading-relaxed">{section.content}</div>}</div>); })}
          </div>
          <div className="mt-16 bg-gradient-to-br from-blue-900 to-slate-900 rounded-3xl p-12 text-white text-center"><h2 className="text-3xl font-bold mb-4">Prêt à déménager sereinement ?</h2><p className="text-xl text-blue-100 mb-8">Notre équipe support est là pour vous aider</p><div className="flex flex-col sm:flex-row gap-4 justify-center items-center"><a href="mailto:support@trouvetondemenageur.fr" className="bg-white text-blue-600 px-8 py-4 rounded-xl font-bold text-lg hover:bg-blue-50 transition-all duration-300 transform hover:scale-105">support@trouvetondemenageur.fr</a><a href="tel:0189707881" className="flex items-center gap-3 bg-blue-700 text-white px-8 py-4 rounded-xl font-bold text-lg hover:bg-blue-600 transition-all duration-300 transform hover:scale-105 border border-blue-500"><Phone className="w-5 h-5" />01 89 70 78 81</a></div></div>
        </main>
      </div>
    </div>
  );
}
